<a href="https://colab.research.google.com/github/bybimasakti/Array/blob/main/Belajar%20List%20Numpy" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Membuat vector
list_array = np.array([1,2,3,4,5,])
print(list_array)

[1 2 3 4 5]


In [ ]:
# Membuat data matrix atau multi vector
data_vector = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(data_vector)
print(data_vector*2) # Akan mengkalikan dua semua nilai didalam list

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [ ]:
# Membuat matrix dengan nol
data_zeros = np.zeros((3,3))
print(data_zeros)
print("\n")
# Membuat matrix dengan 1
data_ones = np.ones((3,4))
print(data_ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Membuat data vector range
data_range1 = np.arange(1,10)
data_range2 = np.arange(1,10,2)
print(data_range1)
print(data_range2)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [1]:
# Membuat Line Space
data_linespace = np.linspace(1,10,4) # Angka 4 merupakan pembagi
print(data_linespace)

NameError: name 'np' is not defined

In [2]:
print("coba2 dlu")

coba2 dlu
